# This file is intended for the shared infrastructures, so reduce the computational burden by testing simgrid only

variables:
    GIT_SUBMODULE_STRATEGY: none

stages:
    - newbuild

simgrid:
    stage: newbuild
    needs: []
    script:
        - mkdir -p logs/simgrid
        - touch logs/simgrid/trust_the_installation trust_the_installation # Silence the checks for the right docker image
        - python3 ./MBI.py -c generate
        - python3 ./MBI.py -x simgrid
        - python3 ./MBI.py -c html
        - pwd ; ls
        - mkdir public
        - cp -r *.html gencodes img logs public/
    image:
        name: simgrid/tuto-mc
        entrypoint: ['/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
    artifacts:
        untracked: false
        when: always
        paths:
            - public
