# This file is intended for the shared infrastructures, so reduce the computational burden by testing simgrid only

variables:
    GIT_SUBMODULE_STRATEGY: none

stages:
    - newbuild

simgrid:
    stage: newbuild
    needs: []
    script:
        - rm -rf /MBI/*; scripts/ensure_python3 ./MBI.py -c generate
        - scripts/ensure_python3 ./MBI.py -x simgrid
        - scripts/ensure_python3 ./MBI.py -c html
        - pwd ; ls
        - mkdir public
        - cp -r *.html gencodes img logs public/
    image:
        name: simgrid/unstable
        entrypoint: ['/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
    artifacts:
        untracked: false
        when: always
        paths:
            - public
