#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"
rootdir=$(pwd)

cd ISP/isp-0.3.1
quilt push -a # Install our patches
./configure --prefix=${rootdir}/builds/ISP --with-mpi-inc-dir=/usr/lib/x86_64-linux-gnu/mpich/include
sed -i "s/-source 1.5 -target 1.5 -classpath/-source 1.7 -target 1.7 -classpath/" UI/Makefile*
make -j$(nproc) install
