#! /usr/bin/python3
import re,sys

template = """// @{generatedby}@
/* ///////////////////////// The MPI Bugs Initiative ////////////////////////

  Origin: MBI

  Description: @{shortdesc}@
    @{longdesc}@

BEGIN_MPI_FEATURES
  P2P:   Lacking
  iP2P:  Lacking
  PERS:  Lacking
  COLL:  @{collfeature}@
  iCOLL: @{icollfeature}@
  TOPO:  Lacking
  RMA:   Lacking
  PROB:  Lacking
  COM:   Lacking
  GRP:   Lacking
  DATA:  Lacking
  OP:    Lacking
END_MPI_FEATURES

BEGIN_ERROR_LABELS
  deadlock:  ???
  numstab:   never
  mpierr:    never
  resleak:   never
  datarace:  never
  various:   never
END_ERROR_LABELS

BEGIN_MBI_TESTS
  $ mpirun -np 2 ${EXE}
  | @{outcome}@
  | @{errormsg}@
END_MBI_TESTS
//////////////////////       End of MBI headers        /////////////////// */

#include <mpi.h>
#include <stdio.h>

int main(int argc, char **argv) {
  int nprocs = -1;
  int rank = -1;
  int localsum, sum;

  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  printf("Hello from rank %d \\n", rank);

  if (nprocs < 2)
    printf("\\033[0;31m! This test needs at least 2 processes to produce a bug "
           "!\\033[0;0m\\n");

  localsum = 0;
  for (int i = 0; i <= rank; i++) {
    localsum += i;
  }
  printf("process %d has local sum of %d\\n", rank, localsum);

  if (rank % 2) {
    @{operation1a}@ /* MBIERROR1 */
    @{operation2a}@
  } else {
    @{operation2b}@ /* MBIERROR2 */
    @{operation1b}@
  }

  if (rank == 0)
    printf("total sum is %d\\n", sum);

  MPI_Finalize();
  printf("\\033[0;32mrank %d Finished normally\\033[0;0m\\n", rank);
  return 0;
}
"""

def find_line(content, target, filename):
  res = 1
  for line in content.split('\n'):
    if re.search(f'[^:]{target}', line):
      #print(f'Found {target} at {line}')
      return res
    res += 1
  raise Exception(f"Line target {target} not found in {filename}.")

def make_file(filename, replace):
  output = template
  filename = re.sub("_MPI_","_", filename)
  replace['filename'] = filename
  # Replace all variables that don't have a ':' in their name
  while re.search("@\{[^@:]*\}@", output):
    m = re.search("@\{([^@:]*)\}@", output)
    target = m.group(1)
    #print(f"Replace @{{{target}}}@")
    if target in replace.keys():
      output = re.sub(f'@\{{{target}\}}@', replace[target], output)
      #print(f"Replace {target} -> {replace[target]}")    
    else:
      raise Exception(f"Variable {target} used in template, but not defined.")
  # Now replace all variables with a ':' in their name: line targets are like that, and we don't want to resolve them before the others change the lines
  while re.search("@\{([^:@]*):([^@]*)\}@", output):
    m = re.search("@\{([^:@]*):([^@]*)\}@", output)
    (kind, target) = (m.group(1), m.group(2))
    if kind == 'line':
      replace = f'{find_line(output, target, filename)}'
      #print(f"Replace @{{line:{target}}}@ with '{replace}'")
      output = re.sub(f'@\{{line:{target}\}}@', replace, output)
    else:
      raise Exception(f"Unknown variable kind: {kind}:{target}")
  # Ready to output it
  with open(filename, 'w') as outfile:
    outfile.write(output)

collectives = ['MPI_Barrier', 'MPI_Reduce']#, 'allreduce']
icollectives = []#'ibarrier', 'ireduce', 'iallreduce']

init = {}
operation = {}

init['MPI_Barrier'] = lambda n: ""
operation['MPI_Barrier'] = lambda n: 'MPI_Barrier(MPI_COMM_WORLD);'

init['MPI_Reduce'] = lambda n: f"int sum{n}, val{n} = 1;"
operation['MPI_Reduce'] = lambda n: f"MPI_Reduce(&sum{n}, &val{n}, 1, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);"

for coll1 in collectives + icollectives:
  for coll2 in collectives + icollectives:
    patterns = {}
    patterns = {'coll1': coll1, 'coll2': coll2}
    patterns['generatedby'] = f'DO NOT EDIT: this file was generated by {sys.argv[0]}. DO NOT EDIT.'
    patterns['collfeature'] = 'Correct' if coll1 in collectives or coll2 in collectives else 'Lacking'
    patterns['icollfeature'] = 'Correct' if coll1 in icollectives or coll2 in icollectives else 'Lacking'
    patterns['coll1'] = coll1
    patterns['coll2'] = coll2
    patterns['init1'] = init[coll1]("1")
    patterns['init2'] = init[coll2]("2")
    patterns['operation1a'] = operation[coll1]("1")
    patterns['operation1b'] = operation[coll1]("1")
    patterns['operation2a'] = operation[coll2]("2")
    patterns['operation2b'] = operation[coll2]("2")

    if coll1 == coll2:
      replace = patterns
      replace['shortdesc'] = 'Correct collective ordering'
      replace['longdesc'] = f'All ranks call {coll1} twice'
      replace['outcome'] = 'OK'
      replace['errormsg'] = ''
      make_file(f'CollectiveOrder_{coll1}_{coll2}.c', replace)
    else: 
      # Generate the correct ordering
      replace = patterns
      replace['shortdesc'] = 'Correct collective ordering'
      replace['longdesc'] = f'All ranks call {coll1} and then {coll2}'
      replace['outcome'] = 'OK'
      replace['errormsg'] = ''
      make_file(f'CollectiveOrder_{coll1}_{coll2}_ok.c', replace)

      # Generate the incorrect ordering
      replace = patterns
      replace['shortdesc'] = 'Incorrect collective ordering'
      replace['longdesc'] = f'Odd ranks call {coll1} and then {coll2} while even ranks call these collectives in the other order'
      replace['outcome'] = 'ERROR: CollectiveOrdering'
      replace['errormsg'] = 'Collective mistmatch. @{coll1}@ at @{filename}@:@{line:MBIERROR1}@ is matched with @{coll2}@ line @{filename}@:@{line:MBIERROR2}@.'

      replace['operation1b'] = operation[coll1]("2") # Inversion
      replace['operation2b'] = operation[coll2]("1")
      make_file(f'CollectiveOrder_{coll1}_{coll2}_nok.c', replace)
