#!/bin/bash

# This file is part of MUST (Marmot Umpire Scalable Tool)
#
# Copyright (C)
#   2011-2014 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
#   2011-2014 Lawrence Livermore National Laboratories, United States of America
#   2013-2014 RWTH Aachen University, Federal Republic of Germany
#
# See the LICENSE file in the package base directory for details


for i in $(ipcs -m | grep ${USER} | grep -v '0x00000000' | awk '{print $1}')
do 
	ipcrm -M $i 
done

for i in $(ipcs -q | grep ${USER} | awk '{print $1}')
do 
	ipcrm -Q $i 
done
