#! /bin/bash

# Check that we have the right image
# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

set -e # Fail on error

# Run the script on each code
python3.8 ${rootdir}/MBI.py -x aislinn $(ls ${rootdir}/codes/*.c)
