#! /bin/bash

# Check that we have the right image
source /etc/os-release
if [ "$VERSION_ID" == "18.04" ] && [ "$ID" == "ubuntu" ] 
then 
   echo "This is an Ubuntu 18.04 OS. Good."
else
   echo "Please run this script in a ubuntu:18.04 image. Run these commands:"
   echo "  docker image pull ubuntu:18.04"
   echo '  docker run -it --rm --name MIB --volume $(pwd):/MBI ubuntu:18.04 /MBI/scripts/Aislinn-run'
   exit 1
fi

# Check that we have the dependencies
apt-get update
apt-get install -y python3.8 gcc python2.7 python-jinja2 #autotools-dev automake build-essential git

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi

export PATH=$PATH:${rootdir}/tools/aislinn-git/bin/

ident=$(date +%s)
rm -rf log/aislinn-${ident} ; mkdir -p log/aislinn-${ident}
cd log/aislinn-${ident}

# Run the script on each code
for file in $(ls ${rootdir}/codes/*.c)
do
    python3.8 ${rootdir}/scripts/runner.py -x aislinn -o bench_aislinn.csv -t 300 --job $CI_JOB_ID $file
done

