#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# Check for updates
if [ -e tools/aislinn-git/.git ]
then
    cd tools/aislinn-git
    git pull
    cd ../..
else
    rm -rf tools/aislinn-git
    git clone --depth=1 https://github.com/spirali/aislinn.git tools/aislinn-git
fi
cp -r ./tools/aislinn-valgrind-312 ./tools/aislinn-git/valgrind  
cd tools/aislinn-git/valgrind
sh autogen.sh
./configure
make -j$(nproc)
cd ../
./waf configure
./waf
