#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../../
rootdir=$(pwd)

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi

export PATH=$PATH:${rootdir}/Aislinn/aislinn-git/bin/

cd Src
# Clean potential logs from previous failed executions
rm -f -r *.html *.csv *.txt *.bc

# Run the script on each code
for file in $(ls ${rootdir}/Src/Benchmarks/*.c)
do
    python3.8 runner.py -x aislinn -o bench_aislinn.csv -t 300 --job $CI_JOB_ID $file
done

# Create log directories
cd ${rootdir}
mkdir -p Log
cd Log
ident=$(date +%s)
mkdir Aislinn-${ident}

# Move every logs at the right location
cd ${rootdir}
cp ./Src/*.html ./Log/Aislinn-${ident}
cp ./Src/*.csv ./Log/Aislinn-${ident}
cp ./Src/*.txt ./Log/Aislinn-${ident}
cd Src
rm -f -r *.html *.csv *.txt *.bc

