#! /bin/bash

# Check that we have the right image
source /etc/os-release
if [ "$VERSION_ID" == "18.04" ] && [ "$ID" == "ubuntu" ] 
then 
   echo "This is an Ubuntu 18.04 OS. Good."
else
   echo "Please run this script in a ubuntu:18.04 image"
   echo "docker image pull ubuntu:18.04"
   echo "docker -it --rm --name MIB --volume .:/MBI ubuntu:18.04 bash"
   exit 1
fi

# Check that we have the dependencies
git_status=`dpkg -l git|grep git|cut -d' ' -f1`
if [ ${git_status} = 'ii' ] 
then
   echo "git is installed. Good"
else
   apt-get update
   apt-get install -y gcc python2.7 python3.8 python-jinja2 autotools-dev automake build-essential git
fi

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# Check for updates
if [ -e tools/aislinn-git/.git ]
then
    cd tools/aislinn-git
    git pull
    cd ../..
else
    rm -rf tools/aislinn-git
    git clone --depth=1 https://github.com/spirali/aislinn.git tools/aislinn-git
fi
cp -r ./tools/aislinn-valgrind-312 ./tools/aislinn-git/valgrind  
cd tools/aislinn-git/valgrind
sh autogen.sh
./configure
make -j$(nproc)
cd ../
./waf configure
./waf
