#! /bin/sh

# Check that we have the right image
if [ -e /MBI ] 
then 
   echo "This seems to be a MBI docker image. Good."
else
   echo "Please run this script in a MBI docker image. Run these commands:"
   echo "  docker build -f Dockerfile -t mpi-bugs-initiative:latest . # Only the first time"
   echo '  docker run -it --rm --name MIB --volume $(pwd):/MBI mpi-bugs-initiative /MBI/scripts/CIVL-run'
   exit 1
fi

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi


ident=$(date +%s)
rm -rf log/civl-${ident} ; mkdir -p log/civl-${ident}
cd log/civl-${ident}

# Get the list of codes from the command line, if it was provided
if [ $# -eq 0 ] 
then
  codes_list=$(ls ${rootdir}/codes/*.c)
else
  codes_list=$@
fi

# Run the script on each code
for file in ${codes_list}
do
    python3.8 ${rootdir}/scripts/runner.py -x civl -o bench_civl.csv -t 300 --job $CI_JOB_ID $file
    killall java || true
done

