#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi


ident=$(date +%s)
rm -rf log/civl-${ident} ; mkdir -p log/civl-${ident}
cd log/civl-${ident}

# Run the script on each code
for file in $(ls ${rootdir}/codes/*.c)
do
    python3.8 ${rootdir}/scripts/runner.py -x civl -o bench_civl.csv -t 300 --job $CI_JOB_ID $file
    killall java || true
done

