#! /usr/bin/python3
import sys
from generator_utils import *

template = """// @{generatedby}@
/* ///////////////////////// The MPI Bugs Initiative ////////////////////////

  Origin: MBI

  Description: @{shortdesc}@
    @{longdesc}@

BEGIN_MPI_FEATURES
	P2P!basic: Lacking
	P2P!nonblocking: Lacking
	P2P!persistent: Lacking
	COLL!basic: @{collfeature}@
	COLL!nonblocking: @{icollfeature}@
	COLL!persistent: Lacking
	COLL!tools: Lacking
	RMA: Lacking
END_MPI_FEATURES

BEGIN_MBI_TESTS
  $ mpirun -np 2 ${EXE}
  | @{outcome}@
  | @{errormsg}@
END_MBI_TESTS
//////////////////////       End of MBI headers        /////////////////// */

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#define buff_size 128


int main(int argc, char **argv) {
  int nprocs = -1;
  int rank = -1;

  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  printf("Hello from rank %d \\n", rank);

  if (nprocs < 2)
    printf("MBI ERROR: This test needs at least 2 processes to produce a bug!\\n");

  MPI_Op op = MPI_SUM;
	MPI_Comm newcom = MPI_COMM_WORLD;
  MPI_Datatype type = MPI_INT;
  @{change_type}@

  int dbs = sizeof(int)*nprocs; /* Size of the dynamic buffers for alltoall and friends */	
  @{init}@
  @{start}@
  @{operation}@ /* MBIERROR */
	@{fini}@
	@{free}@

  MPI_Finalize();
  printf("Rank %d finished normally\\n", rank);
  return 0;
}
"""


for c in coll + icoll + ibarrier:
    patterns = {}
    patterns = {'c': c}
    patterns['generatedby'] = f'DO NOT EDIT: this file was generated by {sys.argv[0]}. DO NOT EDIT.'
    patterns['collfeature'] = 'Yes' if c in coll else 'Lacking'
    patterns['icollfeature'] = 'Yes' if c in icoll + ibarrier else 'Lacking'
    patterns['c'] = c
    patterns['init'] = init[c]("1")
    patterns['start'] = start[c]("1")
    patterns['fini'] = fini[c]("1")
    patterns['operation'] = operation[c]("1")
    patterns['free'] = free[c]("1")

    # Generate the incorrect matching
    replace = patterns
    replace['shortdesc'] = 'Collective @{c}@ with a datatype mismatch'
    replace['longdesc'] = f'Odd ranks use MPI_INT as the datatype while even ranks use MPI_FLOAT'
    replace['outcome'] = 'ERROR: DatatypeMatching'
    replace['errormsg'] = 'Collective datatype mistmatch. @{c}@ at @{filename}@:@{line:MBIERROR}@ has MPI_INT or MPI_FLOAT as a datatype.'
    replace['change_type'] = 'if (rank % 2)\n    type = MPI_FLOAT;'
    make_file(template, f'CollDataMatching_{c}_nok.c', replace)

    # Generate the call with null type
    replace = patterns
    replace['shortdesc'] = 'Collective @{c}@ with an invalid datatype '
    replace['longdesc'] = 'Collective @{c}@ with an invalid datatype ' 
    replace['outcome'] = 'ERROR: InvalidDatatype'
    replace['errormsg'] = 'Invalid Datatype. @{c}@ at @{filename}@:@{line:MBIERROR}@ has an invalid datatype.'
    replace['change_type'] = 'type=MPI_DATATYPE_NULL;'
    make_file(template, f'CollDataNull_{c}_nok.c', replace)
