#! /bin/bash

# Try to use one of the python binaries existing on this machine
for candidate in `which python3.8` `which python3.7` `which python3` `which python` 
do
    if $candidate <<EOF
import sys
if sys.version_info < (3, 7):
    sys.exit(1)
sys.exit(0)
EOF
    then
        exec $candidate $@
    fi
done

# Try to guess the used docker image, and install the missing packages from it
if [ -e /etc/os-release ] 
then
    source /etc/os-release
    if [ "$VERSION_ID" == "18.04" ] && [ "$ID" == "ubuntu" ] 
    then 
        echo "This is an Ubuntu 18.04 OS. Assuming an Aislinn run."
        apt-get update
        apt-get install -y python3.8
        exec python3.8 $@
    fi
fi

if [ -e /root/mpi-sv/mpisv ]
then
    echo "MPI-SV image detected. Good."
    apt-get update
    apt-get install -y software-properties-common # First install add-apt-repository
    echo|add-apt-repository ppa:fkrull/deadsnakes # Add a source for the python we need
    apt-get update
    apt-get install -y python3.6
    exec python3.6 $@
fi

echo "Please run this script from the relevant MBI image."
if echo $@ | grep -qi aislinn 
then
    get="docker image pull ubuntu:18.04"
    img=ubuntu:18.04
elif echo $@ | grep -qi mpisv
then
    get="docker image pull mpisv/mpi-sv"
    img=mpisv/mpi-sv
else
    get="docker build -f Dockerfile -t mpi-bugs-initiative:latest . # Only the first time"
    img=mpi-bugs-initiative
fi
echo "  $get"
echo '  docker run -it --rm --name MIB --volume $(pwd):/MBI '"$img /MBI/MBI.py $@"
exit 1
