#! /bin/sh

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# Check that we have the right image
if [ -e /MBI ] 
then 
   echo "This seems to be a MBI docker image. Good."
else
   echo "Please run this script in a MBI docker image. Run these commands:"
   echo "  docker build -f Dockerfile -t mpi-bugs-initiative:latest . # Only the first time"
   echo "  docker run -it --rm --name MIB --volume $(pwd):/MBI mpi-bugs-initiative /MBI/scripts/ISP-run"
   exit 1
fi

set -e # Fail on error

export PATH=$PATH:${rootdir}/builds/ISP/bin/

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi

test -e ${rootdir}/logs/isp || mkdir -p ${rootdir}/logs/isp
cd ${rootdir}/logs/isp

# Run the script on each code
python3.8 ${rootdir}/scripts/runner.py -x isp -o bench_isp.csv -t 300 --job $CI_JOB_ID $(ls ${rootdir}/codes/*.c)

# Remove generated cruft (binary files)
find -executable | xargs rm
