#! /bin/sh

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

set -e # Fail on error

export PATH=$PATH:${rootdir}/builds/ISP/bin/

test -e ${rootdir}/logs/isp || mkdir -p ${rootdir}/logs/isp
cd ${rootdir}/logs/isp

# Run the script on each code
python3 ${rootdir}/MBI.py -x isp $(ls ${rootdir}/codes/*.c)

# Remove generated cruft (binary files)
find -type f -a -executable | xargs rm -f
