#! /bin/bash

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

set -e # Fail on error

# Check that we have the dependencies: our scripts need python 3.6 that is not available without PPA on Ubuntu 14.04
apt-get update
apt-get install -y software-properties-common # First install add-apt-repository
echo|add-apt-repository ppa:deadsnakes/ppa      # Add a source for the python we need
apt-get update
apt-get install -y python3.7

# Get the list of codes from the command line, if it was provided
if [ $# -eq 0 ] 
then
  codes_list=$(ls ${rootdir}/codes/*.c)
else
  codes_list=$@
fi

# Run the script on each code
python3.7 ${rootdir}/MBI.py -x mpisv ${codes_list}

# Remove generated cruft (temp files and compiled binaries)
#find -executable | xargs rm
