#! /bin/bash

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

set -e # Fail on error

# Check that we have the dependencies: our scripts need python 3.6 that is not available without PPA on Ubuntu 14.04
apt-get update
apt-get install -y software-properties-common # First install add-apt-repository
echo|add-apt-repository ppa:deadsnakes/ppa      # Add a source for the python we need
apt-get update
apt-get install -y python3.7

# Run the script on each code
python3.7 ${rootdir}/MBI.py -x mpisv $@
