#! /bin/sh

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

set -e # Fail on error

export PATH=${rootdir}/builds/MUST/bin:$PATH

# Get the list of codes from the command line, if it was provided
if [ $# -eq 0 ] 
then
  codes_list=$(ls ${rootdir}/codes/*.c)
else
  codes_list=$@
fi

# Run the script on each code
python3 ${rootdir}/MBI.py -x must ${codes_list}

# Remove generated cruft (temp files and compiled binaries)
rm -rf must_temp
find -type f -a -executable | xargs rm -f
