#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../../
rootdir=$(pwd)

cd Must/MUST-v1.6
mkdir -p BUILD
cd BUILD
cmake --version
CC=$(which gcc) CXX=$(which gcc++) FC=$(which gfortran) cmake ../ -DCMAKE_INSTALL_PREFIX=${rootdir}/Must/MUST-v1.6 -DCMAKE_BUILD_TYPE=Release
make -j$(nproc) install VERBOSE=1
