#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

export PATH=${rootdir}/builds/MUST/bin:$PATH

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi

ident=$(date +%s)
rm -rf log/must-${ident} ; mkdir -p log/must-${ident}
cd log/must-${ident}

# Get the list of codes from the command line, if it was provided
if [ $# -eq 0 ] 
then
  codes_list=$(ls ${rootdir}/codes/*.c)
else
  codes_list=$@
fi

# Run the script on each code
for file in ${codes_list}
do
    python3.8 ${rootdir}/scripts/runner.py -x must -o bench_must.csv -t 300 --job $CI_JOB_ID $file
    killall mpirun || true
done
