#! /bin/sh

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# Check that we have the right image
if [ -e /MBI ] 
then 
   echo "This seems to be a MBI docker image. Good."
else
   echo "Please run this script in a MBI docker image. Run these commands:"
   echo "  docker build -f Dockerfile -t mpi-bugs-initiative:latest . # Only the first time"
   echo "  docker run -it --rm --name MIB --volume $(pwd):/MBI mpi-bugs-initiative /MBI/scripts/MUST-build"
   exit 1
fi

set -e # Fail on error

rm -rf /tmp/build-must ; mkdir /tmp/build-must
cd /tmp/build-must

cmake --version
CC=$(which gcc) CXX=$(which gcc++) FC=$(which gfortran) cmake ${rootdir}/tools/MUST-v1.7 -DCMAKE_INSTALL_PREFIX=${rootdir}/builds/MUST -DCMAKE_BUILD_TYPE=Release
make -j$(nproc) install VERBOSE=1
