#! /usr/bin/python3
import os
import sys
from generator_utils import *

template = """// @{generatedby}@
/* ///////////////////////// The MPI Bugs Initiative ////////////////////////

  Origin: MBI

  Description: @{shortdesc}@
    @{longdesc}@

  Version of MPI: Conforms to MPI 1.1, does not require MPI 2 implementation

BEGIN_MPI_FEATURES
  P2P!basic: @{p2pfeature}@
  P2P!nonblocking: @{ip2pfeature}@
  P2P!persistent: Lacking
  COLL!basic: @{collfeature}@
  COLL!nonblocking: Lacking
  COLL!persistent: Lacking
  COLL!tools: Lacking
  RMA: Lacking
END_MPI_FEATURES

BEGIN_MBI_TESTS
  $ mpirun -np 4 ${EXE}
  | @{outcome}@
  | @{errormsg}@
END_MBI_TESTS
//////////////////////       End of MBI headers        /////////////////// */

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#define N 10

int main(int argc, char **argv) {
  int nprocs = -1;
  int rank = -1;
  int dest, src;
  int i=0;
  int root = 0;
  int stag = 0, rtag = 0;
  int buff_size = 1;

  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  printf("Hello from rank %d \\n", rank);

  if (nprocs != 4)
    printf("MBI ERROR: This test needs 4 processes to produce a bug!\\n");

  int dbs = sizeof(int)*nprocs; /* Size of the dynamic buffers for alltoall and friends */
  MPI_Comm newcom = MPI_COMM_WORLD;
  MPI_Datatype type = MPI_INT;
  MPI_Op op = MPI_SUM;

  @{init0a}@
  @{init0b}@
  @{init0c}@
  @{init1a}@
  @{init1b}@
  @{init3a}@
  @{init3b}@
  @{init3c}@
  @{init3d}@

  if (rank == 0) {
    src = MPI_ANY_SOURCE;
    for (int i = 0; i < 2 * N; i++) {
      @{operation0a}@ /* MBIERROR1 */
      @{fini0a}@
    }
    @{opbarrier}@
    src = 3;
    @{operation0b}@ /* MBIERROR2 */
    @{fini0b}@
    @{operation0c}@
    @{fini0c}@
  } else if (rank == 1 || rank == 2) {
    dest = 0;
    for (int i = 0; i < N; i++) {
      @{operation1a}@
      @{fini1a}@
    }
    @{opbarrier}@
    dest = 3;
    @{operation1b}@
    @{fini1b}@
  } else if (rank == 3) {
    @{opbarrier}@
    dest = 0;
    src = 1;
    @{operation3a}@
    @{fini3a}@
    @{operation3b}@
    @{fini3b}@
    src = 2;
    @{operation3c}@
    @{fini3c}@
    @{operation3d}@
    @{fini3d}@
  }

  @{free0a}@
  @{free0b}@
  @{free0c}@
  @{free1a}@
  @{free1b}@
  @{free3a}@
  @{free3b}@
  @{free3c}@
  @{free3d}@

  MPI_Finalize();
  printf("Rank %d finished normally\\n", rank);
  return 0;
}
"""


for s in send + isend:
    for r in recv + irecv:
        for c in barrier:
            patterns = {}
            patterns = {'s': s, 'r': r, 'c': c}
            patterns['generatedby'] = f'DO NOT EDIT: this file was generated by {os.path.basename(sys.argv[0])}. DO NOT EDIT.'
            patterns['p2pfeature'] = 'Yes' if s in send or r in recv else 'Lacking'
            patterns['ip2pfeature'] = 'Yes' if s in isend or r in irecv else 'Lacking'
            patterns['collfeature'] = 'Yes' if c in coll else 'Lacking'
            patterns['s'] = s
            patterns['r'] = r
            patterns['c'] = c
            patterns['opbarrier'] = operation[c]("1")

            patterns['init0a'] = init[r]("0a")
            patterns['init0b'] = init[r]("0b")
            patterns['init0c'] = init[r]("0c")
            patterns['operation0a'] = operation[r]("0a")
            patterns['operation0b'] = operation[r]("0b")
            patterns['operation0c'] = operation[r]("0c")
            patterns['fini0a'] = fini[r]("0a")
            patterns['fini0b'] = fini[r]("0b")
            patterns['fini0c'] = fini[r]("0c")
            patterns['free0a'] = free[r]("0a")
            patterns['free0b'] = free[r]("0b")
            patterns['free0c'] = free[r]("0c")

            patterns['init1a'] = init[s]("1a")
            patterns['init1b'] = init[s]("1b")
            patterns['operation1a'] = operation[s]("1a")
            patterns['operation1b'] = operation[s]("1b")
            patterns['fini1a'] = fini[s]("1a")
            patterns['fini1b'] = fini[s]("1b")
            patterns['free1a'] = free[s]("1a")
            patterns['free1b'] = free[s]("1b")

            patterns['init3a'] = init[r]("3a")
            patterns['init3b'] = init[s]("3b")
            patterns['init3c'] = init[r]("3c")
            patterns['init3d'] = init[s]("3d")
            patterns['operation3a'] = operation[r]("3a")
            patterns['operation3b'] = operation[s]("3b")
            patterns['operation3c'] = operation[r]("3c")
            patterns['operation3d'] = operation[s]("3d")
            patterns['fini3a'] = fini[r]("3a")
            patterns['fini3b'] = fini[s]("3b")
            patterns['fini3c'] = fini[r]("3c")
            patterns['fini3d'] = fini[s]("3d")
            patterns['free3a'] = free[r]("3a")
            patterns['free3b'] = free[s]("3b")
            patterns['free3c'] = free[r]("3c")
            patterns['free3d'] = free[s]("3d")

            # Generate the correct matching because of the conditional
            replace = patterns
            replace['shortdesc'] = 'Message race'
            replace['longdesc'] = 'Message race without problem in @{r}@ with @{c}@.'
            replace['outcome'] = 'OK'
            replace['errormsg'] = 'OK'
            make_file(template, f'MessageRace_Loop_{c}_{s}_{r}_ok.c', replace)

            # Generate the incorrect matching because of the conditional
            replace = patterns
            replace['shortdesc'] = 'Message race'
            replace['longdesc'] = 'Message race in @{r}@ with @{s}@.'
            replace['outcome'] = 'ERROR: MessageRace'
            replace['errormsg'] = 'Message race. The use of wildcard receive calls (@{r}@ at @{filename}@:@{line:MBIERROR1}@ and @{r}@ without wildcard at @{filename}@:@{line:MBIERROR2}@) leads to nondeterministic matching.'
            replace['collfeature'] = 'Lacking'
            replace['opbarrier'] = ''
            make_file(template, f'MessageRace_Loop_{s}_{r}_nok.c', replace)
