#! /usr/bin/python3
import sys
from generator_utils import make_file

template = """// @{generatedby}@
/* ///////////////////////// The MPI Bugs Initiative ////////////////////////

  Origin: MBI

  Description: @{shortdesc}@
    @{longdesc}@

BEGIN_MPI_FEATURES
	P2P!basic: @{p2pfeature}@ 
	P2P!nonblocking: @{ip2pfeature}@
	P2P!persistent: Lacking
	COLL!basic: Lacking
	COLL!nonblocking: Lacking
	COLL!persistent: Lacking
	COLL!tools: Lacking
	RMA: Lacking
END_MPI_FEATURES

BEGIN_MBI_TESTS
  $ mpirun -np 2 ${EXE}
  | @{outcome}@
  | @{errormsg}@
END_MBI_TESTS
//////////////////////       End of MBI headers        /////////////////// */

#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

#define buff_size 128

int main(int argc, char **argv) {
  int nprocs = -1;
  int rank = -1;
	MPI_Status sta;
	int src,dest;

  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &nprocs);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  printf("Hello from rank %d \\n", rank);

  if (nprocs < 2)
    printf("MBI ERROR: This test needs at least 2 processes to produce a bug!\\n");

  @{init1a}@
  @{init1b}@
  @{init1c}@
  @{init2a}@
  @{init2b}@
  @{init2c}@

	if (rank == 0) {
		dest=1, src=1;
  	@{operation1a}@ /* MBIERROR1 */
  	@{operation1b}@ 
  	@{operation1c}@ 
	}else if (rank == 1){
		dest=0, src=0;
  	@{operation2a}@ /* MBIERROR2 */
  	@{operation2b}@ 
  	@{operation2c}@ 
	}

  MPI_Finalize();
  printf("Rank %d finished normally\\n", rank);
  return 0;
}
"""

p2p = ['MPI_Send', 'MPI_Recv'] 
send = ['MPI_Send'] 
recv = ['MPI_Recv'] 
ip2p = ['MPI_Isend', 'MPI_Irecv']  
isend = ['MPI_Isend']  
irecv = ['MPI_Irecv']  
probe = ['MPI_Probe']

init = {}
operation = {}

init['MPI_Send'] = lambda n: f'int buf{n}[buff_size];'
operation['MPI_Send'] = lambda n: f'MPI_Send(buf{n}, buff_size, MPI_INT, dest, 0, MPI_COMM_WORLD);'

init['MPI_Recv'] = lambda n: f'int buf{n}[buff_size];'
operation['MPI_Recv'] = lambda n: f'MPI_Recv(buf{n}, buff_size, MPI_INT, src, 0, MPI_COMM_WORLD, &sta);'

init['MPI_Isend'] = lambda n: f'int buf{n}[buff_size]; MPI_Request req{n};'
operation['MPI_Isend'] = lambda n: f'MPI_Isend(buf{n}, buff_size, MPI_INT, dest, 0, MPI_COMM_WORLD, &req{n});\n		MPI_Wait(&req{n}, &sta);'

init['MPI_Irecv'] = lambda n: f'int buf{n}[buff_size]; MPI_Request req{n};'
operation['MPI_Irecv'] = lambda n: f'MPI_Irecv(buf{n}, buff_size, MPI_INT, src, 0, MPI_COMM_WORLD, &req{n});\n		MPI_Wait(&req{n}, &sta);'

init['MPI_Probe'] = lambda n: ""
operation['MPI_Probe'] = lambda n: f'MPI_Probe(src, 0, MPI_COMM_WORLD, &sta);'

for p in probe:
    for s in send + isend:
        for r in recv + irecv:
            patterns = {}
            patterns = {'p':p, 's': s, 'r': r}
            patterns['generatedby'] = f'DO NOT EDIT: this file was generated by {sys.argv[0]}. DO NOT EDIT.'
            patterns['p2pfeature'] = 'Yes' if s in send or r in recv else 'Lacking'
            patterns['ip2pfeature'] = 'Yes' if s in isend or r in irecv else 'Lacking'
            patterns['s'] = s
            patterns['r'] = r
            patterns['p'] = p
            patterns['init1a'] = init[p]("1")
            patterns['init1b'] = init[s]("1")
            patterns['init1c'] = init[r]("2")
            patterns['init2a'] = init[p]("1")
            patterns['init2b'] = init[r]("3")
            patterns['init2c'] = init[s]("4")
            patterns['operation1a'] = operation[p]("1")
            patterns['operation1b'] = operation[s]("1")
            patterns['operation1c'] = operation[r]("2")
            patterns['operation2a'] = operation[p]("1")
            patterns['operation2b'] = operation[r]("3")
            patterns['operation2c'] = operation[s]("4")
    
            # Generate the incorrect matching 
            replace = patterns 
            replace['shortdesc'] = 'MPI_Probe is called before MPI_Recv.'
            replace['longdesc'] = f'MPI_Probe is a blocking call that returns only after a matching message has been found. By calling MPI_Probe before MPI_Recv, a deadlock is created.'
            replace['outcome'] = 'ERROR: CallMatching' 
            replace['errormsg'] = 'P2P mistmatch. @{p}@ at @{filename}@:@{line:MBIERROR1}@ and @{filename}@:@{line:MBIERROR2}@ are called before @{r}@.' 
            make_file(template, f'P2PCallMatching_{p}_{r}_{s}_nok.c', replace)

            # Generate a correct matching 
            replace = patterns 
            replace['shortdesc'] = 'Correct use of MPI_Probe.'
            replace['longdesc'] = 'Correct use of MPI_Probe.'
            replace['outcome'] = 'OK' 
            replace['errormsg'] = 'OK'
            replace['operation1a'] = operation[s]("1")
            replace['operation1b'] = operation[p]("1")
            make_file(template, f'P2PCallMatching_{p}_{r}_{s}_ok.c', replace)
