#! /bin/sh

# Check that we have the right image
if [ -e /MBI ] 
then 
   echo "This seems to be a MBI docker image. Good."
else
   echo "Please run this script in a MBI docker image. Run these commands:"
   echo "  docker build -f Dockerfile -t mpi-bugs-initiative:latest . # Only the first time"
   echo '  docker run -it --rm --name MIB --volume $(pwd):/MBI mpi-bugs-initiative /MBI/scripts/Parcoach-run'
   exit 1
fi

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi

ident=$(date +%s)
rm -rf log/parcoach-${ident} ; mkdir -p log/parcoach-${ident}
cd log/parcoach-${ident}

# Run the script on each code
for file in $(ls ${rootdir}/codes/*.c)
do
    python3.8 ${rootdir}/scripts/runner.py -x parcoach -o bench_parcoach.csv -t 300 --job $CI_JOB_ID $file
done

