#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

ln -s $(which clang) /usr/lib/llvm-9/bin/clang

# Check for updates
if [ -e tools/parcoach/.git ]
then
    cd tools/parcoach
    git pull
    cd ../..
else
    rm -rf tools/parcoach
    git clone --depth=1 https://github.com/parcoach/parcoach.git tools/parcoach
fi

rm -rf ${rootdir}/builds/parcoach && mkdir -p ${rootdir}/builds/parcoach
cd ${rootdir}/builds/parcoach

cmake ${rootdir}/tools/parcoach -DCMAKE_C_COMPILER=clang -DLLVM_DIR=${rootdir}/tools/Parcoach/llvm-project/build
make -j$(nproc) VERBOSE=1
ctest --output-on-failure
