#! /usr/bin/python3
import sys
from generator_utils import *

template = """// @{generatedby}@
/* ///////////////////////// The MPI Bugs Initiative ////////////////////////

  Origin: @{origin}@

  Description: @{shortdesc}@
    @{longdesc}@


BEGIN_MPI_FEATURES
  P2P!basic: Lacking
  P2P!nonblocking: Lacking
  P2P!persistent: Lacking
  COLL!basic: Lacking
  COLL!nonblocking: Lacking
  COLL!persistent: Lacking
  COLL!tools: Lacking
  RMA: @{rmafeature}@
END_MPI_FEATURES

BEGIN_MBI_TESTS
  $ mpirun -np 2 ${EXE}
  | @{outcome}@
  | @{errormsg}@
END_MBI_TESTS
//////////////////////       End of MBI headers        /////////////////// */

#include <mpi.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

#define N 10

void get_win(MPI_Win *win) {
  @{bufferalloc}@

  MPI_Win_create(@{buffer}@, N * sizeof(int), 1, MPI_INFO_NULL, MPI_COMM_WORLD, win);

  return;
}

int main(int argc, char *argv[]) {
  int rank, numProcs;

  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &numProcs);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  printf("Hello from rank %d \\n", rank);

  MPI_Win win;

  get_win(&win);

  MPI_Win_free(&win);

  MPI_Finalize();
  printf("Rank %d finished normally\\n", rank);
  return 0;
}

"""


for b in ['stack', 'missing', 'null',  'malloc', 'bufferSize']:
    patterns = {}
    patterns = {'b': b}
    patterns['origin'] = "MPI-CorrBench: ArgErr-MPIWinCreate-invalidBuffer-2.c"
    patterns['generatedby'] = f'DO NOT EDIT: this file was generated by {sys.argv[0]}. DO NOT EDIT.'
    patterns['rmafeature'] = 'Yes'

    replace = patterns
    replace['shortdesc'] = 'Invalid buffer in window creation.'
    replace['longdesc'] = 'Invalid buffer in window creation.'
    replace['outcome'] = 'ERROR: InvalidBuffer'
    replace['errormsg'] = '@{b}@ at @{filename}@:@{line:MBIERROR}@ has an invalid buffer'

    ok = 'nok'
    header = 'InvalidParam'
    replace['buffer'] = 'buffer'

    if b == 'stack':
        replace['bufferalloc'] = 'int buffer[N]; /* MBIERROR1 */'
        replace['buffer'] = '&buffer'
        replace['longdesc'] = 'Use a stack oriented buffer in window creation, buffer on temporary stack memory.'
    elif b == 'missing':
        replace['bufferalloc'] = 'int * buffer; /* MBIERROR1 */'
        replace['longdesc'] = 'Uninitialized buffer in window creation.'
    elif b == 'null':
        replace['bufferalloc'] = 'int * buffer = NULL; /* MBIERROR1 */'
        replace['longdesc'] = 'Use NULL buffer in window creation.'
    elif b == 'bufferSize':
        replace['bufferalloc'] = 'int * buffer = malloc((N/2) * sizeof(int)); /* MBIERROR1 */'
        replace['longdesc'] = 'Unmatched size of buffer in window creation.'
    else:
        replace['bufferalloc'] = 'int * buffer = malloc(N * sizeof(int));'
        replace['longdesc'] = 'Correct initialized buffer in window creation.'
        replace['outcome'] = 'OK'
        replace['errormsg'] = ''
        header = 'RMA'
        ok = 'ok'

    make_file(template, f'{header}_WinBuffer_{b}_{ok}.c', replace)
