#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

export PATH=$PATH:${rootdir}/builds/SimGrid/bin
export VERBOSE=1

# If this was not run with gilab-ci, we provide a meaningless value
if [ -z "$CI_JOB_ID" ]
then
    CI_JOB_ID=0
fi

ident=$(date +%s)
rm -rf log/simgrid-${ident} ; mkdir -p log/simgrid-${ident}
cd log/simgrid-${ident}

cp ${rootdir}/builds/SimGrid/cluster.xml .

# Run the script on each code
for file in $(ls ${rootdir}/codes/*.c)
do
    python3.8 ${rootdir}/scripts/runner.py -x simgrid -o bench_simgrid.csv -t 300 --job $CI_JOB_ID $file
done
