#! /bin/sh

set -e # Fail on error

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# Check for updates
if [ -e tools/simgrid/.git ]
then
    cd tools/simgrid
    git pull
    cd ../..
else
    rm -rf tools/simgrid
    git clone --depth=1 https://framagit.org/simgrid/simgrid.git tools/simgrid
fi

cd ${rootdir}/tools/simgrid
cmake -DCMAKE_INSTALL_PREFIX=${rootdir}/SimGrid-install -Denable_model-checking=ON .
make -j$(nproc) install VERBOSE=1
