#! /bin/sh

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

set -e # Fail on error

# Run the script on each code
python3 ${rootdir}/MBI.py -x simgrid $(ls ${rootdir}/codes/*.c)

# Remove generated cruft (binary files and SMPI temp files)
find -type f -a -executable | xargs rm -f
rm -f smpitmp-*
