#! /bin/sh

# Go to the MBI root directory
cd "$(dirname "$0")"/../
rootdir=$(pwd)

# Check that we have the right image
if [ -e /MBI ]
then
   echo "This seems to be a MBI docker image. Good."
else
   echo "Please run this script in a MBI docker image. Run these commands:"
   echo "  docker build -f Dockerfile -t mpi-bugs-initiative:latest . # Only the first time"
   echo "  docker run -it --rm --name MIB --volume $(pwd):/MBI mpi-bugs-initiative /MBI/scripts/SimGrid-build"
   exit 1
fi

set -e # Fail on error

# Check for updates
if [ -e tools/simgrid/.git ]
then
    cd tools/simgrid
    git pull
    cd ../..
else
    rm -rf tools/simgrid
    git clone --depth=1 https://framagit.org/simgrid/simgrid.git tools/simgrid
fi

cd ${rootdir}/tools/simgrid
cmake -DCMAKE_INSTALL_PREFIX=${rootdir}/builds/SimGrid -Denable_model-checking=ON .
make -j$(nproc) install VERBOSE=1

cp ${rootdir}/tools/simgrid/examples/platforms/cluster_backbone.xml ${rootdir}/builds/SimGrid/cluster.xml
