#! /bin/sh

set -e # Fail on error

# Go to the main MBI/ directory
cd "$(dirname "$0")"/..

./MBI.py -c generate

scripts/CIVL-build
./MBI.py -x civl -c run

scripts/ISP-build
./MBI.py -x isp -c run

scripts/MUST-build
./MBI.py -x must -c run

./MBI.py -x mpisv -c run

scripts/SimGrid-build
./MBI.py -x simgrid -c run

scripts/Parcoach-build
./MBI.py -x parcoach -c run

./MBI.py -c stats
