#! /bin/sh

set -e # Fail on error

# Go to the main MBI/ directory
cd "$(dirname "$0")"/..

./MBI.py -c generate

scripts/CIVL-build
./MBI.py -x civl

scripts/ISP-build
./MBI.py -x isp

scripts/MUST-build
./MBI.py -x must

./MBI.py -x mpisv

scripts/SimGrid-build
./MBI.py -x simgrid

scripts/Parcoach-build
./MBI.py -x parcoach

